# Topic modelling of bundestag speeches of the 20th legislative period


library(tidyr)
library(dplyr)
library(stringfish)
library(stringr)
library(keyATM)
library(quanteda.textstats)
library(quanteda)




bt_speeches <- read.csv("data/all_data_combined.csv")

bt_speeches <- bt_speeches |> group_by(Party) |> mutate(n_party_members = length(unique(MPID)))

bt_speeches <- bt_speeches |> mutate(populist_mean = (Anti.Elitism + People.Centrism + Left.Wing.Host.Ideology + Right.Wing.Host.Ideology)/4)

bt_speeches <- bt_speeches |> mutate(Party = gsub("[^a-zA-Z0-9äöüß/ ]", "", Party))

saveRDS(bt_speeches, "data/bt_speeches.rds")

nrow(bt_speeches)
bt_speeches$doc_id <- seq_len(nrow(bt_speeches))
length(unique(bt_speeches$doc_id))
names_bt_members_list <- unique(bt_speeches$Name) |> list()
names_bt_members <- split(names_bt_members_list[[1]], ceiling(seq_along(names_bt_members_list[[1]])/300))


names_bt_members_rgx <- sapply(names_bt_members, function(names){
  gsub(" \\(.+\\)", "", paste0(names, collapse="|"))
})


removeRegexes <- function(column, regex, n_threads = 4){
  for (n in seq_along(regex)){
    rgx <- regex[n]
    print(paste0("rgx group: ", n, " of ", length(regex)))
    # Source - https://stackoverflow.com/a/78270004
    # Posted by LMc
    # Retrieved 2026-04-08, License - CC BY-SA 4.0
    column <- sf_gsub(column, regex(rgx, ignore_case = TRUE), "", nthreads = n_threads)
  
  }
  return(column)
}

bt_speeches$sentence <- removeRegexes(bt_speeches$sentence, names_bt_members_rgx)

bt_corpus <- corpus(bt_speeches, text_field = "sentence", docid_field = "doc_id")


# Source - https://stackoverflow.com/a/50843894
# Posted by Ken Benoit
# Retrieved 2026-04-29, License - CC BY-SA 4.0

containstarget <- str_detect(bt_corpus, "Drucksachen")
summary(containstarget)
##    Mode   FALSE    TRUE 
## logical    44393     108 

# Source - https://stackoverflow.com/a/50843894
# Posted by Ken Benoit
# Retrieved 2026-04-29, License - CC BY-SA 4.0

bt_corpus_trimmed <- corpus_subset(bt_corpus, !containstarget)

toks <- tokens(
  bt_corpus_trimmed,
  remove_punct = TRUE,
  remove_numbers = FALSE, # some numbers could be relevant as they could refer to specific events (e.g. 100 billion for the Bundeswehr)
  remove_symbols = FALSE
) |>
  tokens_remove(c(stopwords("de"), "kolleginnen",
  "kollegen", "frau", "herr", "damen", "herren", "geehrte", "geehrten", "liebe", "vielen", "dank", "mal", "geehrter", "dr", "dass", "verehrten", "verehrte", "herzlichen", "dank", "ja", "schon", "stimmen", "enthaltungen", "angenommen", "abstimmung", "gestimmt", "ungültige", "neinstimmen", "jastimmen"))




collocations <- textstat_collocations(toks, min_count = 10)
print(collocations[order(-collocations$count),][1:50,])

toks <- tokens_compound(
  toks,
  phrase(c(
    "wer stimmt dagegen",
    "wer stimmt dafür",
    "wer enthält sich",
    "wer stimmt",
    "wer enthält",
    "CDU CSU",
    "CDU csu-fraktion",
    "fraktionen SPD bündnis 90 grünen fdp",
    "fraktion bündnis 90 grünen",
    "bündnis 90 grünen",
    "fraktion CDU CSU",
    "fraktion linke",
    "fraktion SPD",
    "fraktion AfD",
    "fraktion FDP",
    "wladimir putin",
    "europäische union",
    "europäischen union",
    "europäischer union",
    "europäischer rat",
    "europäisches parlament",
    "europäischer gerichtshof",
    "europäische kommission",
    "europäischen kommission",
    "europäische zentralbank",
    "deutschen bundestag",
    "deutscher bundestag",
    "deutsche bundesregierung",
    "demokratische parteien",
    "demokratischen parteien",
    "demokratischen fraktionen",
    "demokratische fraktionen",
    "bürgerinnnen bürger",
    "bürger innen",
    "zuschauer innen",
    "erneuerbare energie",
    "erneuerbare energien",
    "erneuerbaren energien",
    "soziale gerechtigkeit",
    "hartz iv"
  ))
)


toks <- toks |> tokens_remove(c("wer_stimmt_dagegen", "wer_stimmt_dafür", "wer_stimmt", "wer_enthält", "wer_enthält_sich"))



dfm <- dfm(toks)
dfm_trim <- dfm_trim(dfm, min_docfreq = 2, min_termfreq = 2)
dfm_trim_clean <- dfm_subset(dfm_trim, ntoken(dfm_trim) > 0)
keyatm_obj <- keyATM_read(dfm_trim_clean)



# keyatm_model_15 <- weightedLDA(
#   docs = keyatm_obj,
#   number_of_topics = 15,
#   model = "base",
#   options = list(seed = 420)
# )

# top_words(keyatm_model_15, n = 20)

# create a dataframe that includes the topic probabilities for each document
# disclaimer: this code was generated by perplexity and reviewed and turned into a function by the user.:


create_topic_df_LDA <- function(keyatm_model, base_dataframe) {

topic_df <- as.data.frame(keyatm_model$theta)
topic_df$doc_id <- seq_len(nrow(topic_df))


# 3) Reshape the 4 dimensions into long format
sentences_long <- base_dataframe |>
  pivot_longer(
    cols = c(People.Centrism, Anti.Elitism, Left.Wing.Host.Ideology, Right.Wing.Host.Ideology),
    names_to = "dimension",
    values_to = "score"
  )

# 4) Join topic proportions
merged <- sentences_long |>
  left_join(topic_df, by = "doc_id")

# 5) Compute topic-weighted averages for each dimension
topic_dims_long <- merged |>
  pivot_longer(
    cols = starts_with("Topic_"),   # adjust if topic columns have different names
    names_to = "topic",
    values_to = "topic_prob"
  )
  
topic_dim_summary <- topic_dims_long |>
  group_by(topic, dimension) |>
  summarise(
    weighted_mean_score = sum(score * topic_prob, na.rm = TRUE) / sum(topic_prob, na.rm = TRUE),
    mean_score = mean(score, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )


topic_dims_long %>%
  group_by(topic) %>%
  summarise(
    total_topic_weight = sum(topic_prob, na.rm = TRUE),
    mean_topic_prob = mean(topic_prob, na.rm = TRUE),
    sd_topic_prob = sd(topic_prob, na.rm = TRUE)
  )


merged <- dplyr::left_join(bt_speeches, topic_df, by = "doc_id")

merged$top_topic <- max.col(merged[, paste0("Topic_", 1:15)], ties.method = "first")

return(merged)

}

calculate_averages_LDA <- function(merged) {
topic_populism <- merged |>
  dplyr::group_by(top_topic) |>
  dplyr::summarise(
    mean_people_centrism = mean(People.Centrism, na.rm = TRUE),
    share_mean_people_centrism = mean(People.Centrism > 0, na.rm = TRUE),
    
    mean_anti_elitism = mean(Anti.Elitism, na.rm = TRUE),
    share_mean_people_centrism = mean(Anti.Elitism > 0, na.rm = TRUE),
    
    mean_left_wing = mean(Left.Wing.Host.Ideology, na.rm = TRUE),
    share_mean_people_centrism = mean(Left.Wing.Host.Ideology > 0, na.rm = TRUE),
    
    mean_right_wing = mean(Right.Wing.Host.Ideology, na.rm = TRUE),
    share_mean_people_centrism = mean(Right.Wing.Host.Ideology > 0, na.rm = TRUE),

    n = dplyr::n()
  )

long <- merged |>
  pivot_longer(starts_with("Topic_"), names_to = "topic", values_to = "p_topic") |>
  mutate(weighted_people_centrism = People.Centrism * p_topic,
         weighted_anti_elitism = Anti.Elitism * p_topic,
         weighted_left_wing = Left.Wing.Host.Ideology * p_topic,
         weighted_right_wing = Right.Wing.Host.Ideology * p_topic)

topic_populism_soft_weighted <- long |>
  group_by(topic) |>
  summarise(
    weighted_mean_people_centrism = sum(weighted_people_centrism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_anti_elitism = sum(weighted_anti_elitism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_left_wing = sum(weighted_left_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_right_wing = sum(weighted_right_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    n = n()
  )
return(list(hard = topic_populism, soft = topic_populism_soft_weighted))
}


# merged <- create_topic_df(keyatm_model_15, bt_speeches)
# topic_populism_soft_weighted <- calculate_averages(merged)


# disclaimer: github copilot generated most of the keywords for the topic analysis, the user adjusted where necessary.
topics_digitization = list(
              agriculture = c("feld", "landwirtschaft", "bauern", "nahrungsmittel", "lebensmittel"),
              culturemedia = c("kultur", "feiern", "medien", "fernsehen", "radio", "zeitungen"),
              digitalizationtech = c("internet", "digital", "online", "netz", "plattform", "digitalisierung"),
              economy = c("arbeit", "unternehmen", "wirtschaft", "job", "arbeitsplätze", "lohn", "industrie"),
              eudcationscience = c("schule", "bildung", "universität", "forschung", "wissenschaft", "lehrer"),
              environmentclimate = c("klima", "umwelt", "energie", "klimaschutz", "klimawandel", "erneuerbare", "erneuerbare_energien", "erneuerbaren_energien"),
              financetax = c("finanz", "geld", "haushalt", "schulden", "etat", "steuern", "steuer"),
              foreign = c("ausland", "international", "europäisch", "diplomatie", "nato", "china", "amerika", "usa"),
              government = c("regierung", "bundesregierung", "kanzler", "minister", "bundestag", "parlament"),
              party = c("partei", "parteien", "fraktion", "abgeordnete", "mitglied", "wahl", "wahlkampf", "cdu", "csu", "spd", "bündnis_90_grünen", "linke", "afd", "fdp"),
              regional = c("region", "länder", "bundesländer", "kommunen", "städte", "dörfer"),
              security = c("sicherheit", "polizei", "terrorismus", "kriminalität", "sicher"),
              social = c("sozial", "rente", "gesundheit", "pflege", "arbeitslosigkeit", "familie", "soziale_gerechtigkeit"),
              transportinfrastructure = c("verkehr", "infrastruktur", "bahn", "auto", "flughafen", "brücken", "öffentlichen", "autobahn", "schiene", "fahrrad"),
              # additional topics not from the digitization paper
              migration = c("migration", "flüchtlinge", "asyl", "integration", "grenzen", "integrieren"),
              ukraine = c("ukraine", "russland", "krieg", "putin", "angriffskrieg", "invasion", "militärische intervention", "drohnenkrieg", "hybride kriegsführung"),
              procedural = c("tagesordnung", "ergebnis", "überweisungsvorschlag", "antrag", "gesetz", "debatte", "schriftführer", "schriftführerinnen", "drucksache", "präsident", "präsidentin", "ausschuss", "rede", "plenum", "wort", "zwischenfrage", "intervention", "protokoll", "tagesordnungspunkt", "beschlussempfehlung", "aussprache")
              )


topics_local <- list(
              procedural = c("tagesordnung", "ergebnis", "antrag", "gesetz", "debatte", "drucksache", "präsident", "präsidentin", "ausschuss", "rede", "plenum", "wort", "zwischenfrage", "intervention", "protokoll"),
              covid = c("corona", "covid", "pandemie", "impfung", "virus", "infektion", "gesundheitsschutz"),
              migration = c("migration", "flüchtlinge", "asyl", "integration", "grenzen", "integration"),
              social = c("soziale_gerechtigkeit", "sozial", "rente", "arbeitslosigkeit", "familie", "hartz_iv", "grundsicherung", "bürgergeld"),
              economy = c("arbeit", "unternehmen", "wirtschaft", "job", "arbeitsplätze", "lohn", "industrie"),
              eudcationscience = c("schule", "bildung", "universität", "forschung", "wissenschaft", "lehrer"),
              environmentclimate = c("klima", "umwelt", "energie", "klimaschutz", "klimawandel", "erneuerbare", "erneuerbare_energien", "erneuerbaren_energien"),
              financetax = c("finanz", "geld", "haushalt", "schulden", "etat"),
              foreign = c("ausland", "europa", "international", "europäisch", "diplomatie", "nato", "krieg", "ukraine", "russland", "china", "amerika", "usa", "putin"),
              government = c("regierung", "bundesregierung", "kanzler", "minister", "bundestag", "parlament"),
              security = c("sicherheit", "polizei", "verfassungsschutz", "terrorismus", "kriminalität")

)

keyatm_model_digitization <- keyATM(
  keyatm_obj,
  model = "base",
  no_keyword_topics = 2,
  keywords = topics_digitization,
  options = list(seed = 420)
)

top_words(keyatm_model_digitization, n=20)

keyatm_model_local <- keyATM(
  keyatm_obj,
  model = "base",
  no_keyword_topics = 2,
  keywords = topics_local,
  options = list(seed = 420)
)

top_words(keyatm_model_local, n=20)

create_topic_df <- function(keyatm_model, base_dataframe) {
  
  
  # Extract theta as dataframe with doc_id
  topic_df <- as.data.frame(keyatm_model$theta)
  topic_df$doc_id <- seq_len(nrow(topic_df))

  # Reshape sentiment dimensions to long format
  sentences_long <- base_dataframe |>
    pivot_longer(
      cols = c(People.Centrism, Anti.Elitism, Left.Wing.Host.Ideology, Right.Wing.Host.Ideology),
      names_to = "dimension",
      values_to = "score"
    )
  
  # Join with topic proportions
  merged_long <- sentences_long |>
    left_join(topic_df, by = "doc_id") |>
    pivot_longer(
      cols = -c(names(sentences_long)),  # All topic columns
      names_to = "topic",
      values_to = "topic_prob"
    )


  # Compute topic-weighted averages per dimension
  topic_dim_summary <- merged_long |>
    group_by(topic, dimension) |>
    summarise(
      weighted_mean_score = sum(score * topic_prob, na.rm = TRUE) / sum(topic_prob, na.rm = TRUE),
      mean_score = mean(score, na.rm = TRUE),
      n = n(),
      .groups = "drop"
    )
  
  # Topic diagnostics
  topic_diag <- merged_long |>
    group_by(topic) |>
    summarise(
      total_topic_weight = sum(topic_prob, na.rm = TRUE),
      mean_topic_prob = mean(topic_prob, na.rm = TRUE),
      sd_topic_prob = sd(topic_prob, na.rm = TRUE),
      .groups = "drop"
    )
  
  # Main merged df for documents (wide topic format)
  merged <- base_dataframe |>
    left_join(topic_df, by = "doc_id")
  
  # Compute top_topic using max.col (handles any # topics)
  topic_cols <- grep("^(\\d+_|Other_)", names(merged), value = TRUE)  # Non-doc_id columns starting topics
  merged$top_topic <- max.col(merged[, topic_cols], ties.method = "first")
  
  # Optionally return summaries too
  return(list(merged = merged, topic_dim_summary = topic_dim_summary, topic_diag = topic_diag))
}

calculate_averages <- function(merged) {
  # Unweighted (hard-clustering) averages by top_topic
  topic_populism_hard <- merged |>
    group_by(top_topic) |>
    summarise(
      mean_people_centrism = mean(People.Centrism, na.rm = TRUE),
      share_people_centrism = mean(People.Centrism > 0, na.rm = TRUE),
      mean_anti_elitism = mean(Anti.Elitism, na.rm = TRUE),
      share_anti_elitism = mean(Anti.Elitism > 0, na.rm = TRUE),
      mean_left_wing = mean(Left.Wing.Host.Ideology, na.rm = TRUE),
      share_left_wing = mean(Left.Wing.Host.Ideology > 0, na.rm = TRUE),
      mean_right_wing = mean(Right.Wing.Host.Ideology, na.rm = TRUE),
      share_right_wing = mean(Right.Wing.Host.Ideology > 0, na.rm = TRUE),
      n = n(),
      .groups = "drop"
    )
  
  # Weighted (soft) averages
  long <- merged |>
    pivot_longer(
      cols = c(starts_with(c("1_", "2_", "3_", "4_", "5_", "6_", "7_", "8_", "9_", "10_", "11_", "12_", "13_", "14_", "15_", "Other_"))),  # Adjust if topic columns have different names
      names_to = "topic",
      values_to = "p_topic"
    ) |>
    mutate(
      weighted_people_centrism = People.Centrism * p_topic,
      weighted_anti_elitism = Anti.Elitism * p_topic,
      weighted_left_wing = `Left.Wing.Host.Ideology` * p_topic,
      weighted_right_wing = `Right.Wing.Host.Ideology` * p_topic
    )
  
  topic_populism_soft <- long |>
    group_by(topic) |>
    summarise(
      weighted_mean_people_centrism = sum(weighted_people_centrism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
      weighted_mean_anti_elitism = sum(weighted_anti_elitism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
      weighted_mean_left_wing = sum(weighted_left_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
      weighted_mean_right_wing = sum(weighted_right_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
      n = n(),
      .groups = "drop"
    )
  
  return(list(hard = topic_populism_hard, soft = topic_populism_soft))
}

merged_digitization <- create_topic_df(keyatm_model = keyatm_model_digitization, base_dataframe = bt_speeches)
topic_populism_soft_weighted_digitization <- calculate_averages(merged_digitization$merged)

# count how many missing values there are in top_topic
merged_digitization$merged[is.na(merged_digitization$merged$top_topic),] |> View()


saveRDS(merged_digitization, "data/topic_proportions_digitization.rds")
saveRDS(topic_populism_soft_weighted_digitization, "data/topic_populism_soft_weighted_digitization.rds")


# merged_local <- create_topic_df(keyatm_model = keyatm_model_digitization, base_dataframe = bt_speeches)
# topic_populism_soft_weighted_local <- calculate_averages(merged_local$merged)

# saveRDS(topic_populism_soft_weighted_local, "data/topic_populism_soft_weighted_local.rds")

head(merged_digitization)

