---
title: data analysis - The New Sound of Politics
authors:
  - name: Robert Bowien
    affiliation: University College Dublin
    roles: writing
    corresponding: true
bibliography: references.bib
---



# Descriptive Data analysis

## Social Media relevance

The next step is to calculate the proportion of social media as most important information source and then plot the development over time.


```{r}
library(ggplot2)
library(dplyr)

```
```{r}

# data_sm_relevance <- read.csv("data/sm_relevance.csv")
# colnames(data_ts_linechart)
# data_ts_linechart <- data_sm_relevance |> group_by(field_start) |> summarise(prop_sm = mean(m0001_3 == 4))

# ggplot(data = data_ts_linechart, aes(x=field_start, y=prop_sm, group = 1)) +
#   geom_line()


```



## Bundestag Speeches


load the data
```{r}

bt_speeches <- read.csv("data/bundestag_181920.csv")

```
calculate summary statisitics


```{r}

bt_speeches <- bt_speeches |> group_by(Party) |> mutate(n_party_members = length(unique(MPID)))

sum_stat = subset(bt_speeches, select = c("Party", "n_party_members")) |> unique()

print(sum_stat)
print(bt_speeches[bt_speeches$n_party_members == max(bt_speeches$n_party_members),]$Party |> unique())

```

QTA methods
```{r}

bt_speeches|> head()
```




PopBERT evaluation

```{r}
bt_speeches <- bt_speeches |> mutate(Populist_aggregated = (LABEL_0 + LABEL_1 + LABEL_2 + LABEL_3)/4)


names(bt_speeches)[names(bt_speeches) == "LABEL_0"] <- "Anti-Elitism"
names(bt_speeches)[names(bt_speeches) == "LABEL_1"] <- "People-Centrism"
names(bt_speeches)[names(bt_speeches) == "LABEL_2"] <- "Left-Wing-Host-Ideology"
names(bt_speeches)[names(bt_speeches) == "LABEL_3"] <- "Right-Wing-Host-Ideology"
```

```{r}
colnames(bt_speeches)
score_over_time <- ggplot(bt_speeches, aes(x=Date, y=LABEL_0, group=Party, color=Party)) +
geom_point() +
geom_smooth() +
facet_wrap( ~ Party)
score_over_time

```

```{r}
bt_speeches <- bt_speeches |> group_by(MPID) |> mutate(mean_pop_per_speaker = mean(Populist_aggregated))

bt_speeches |> arrange(desc(mean_pop_per_speaker)) |> subset(select=c(MPID, mean_pop_per_speaker, Party, Speech))
```
