---
title: The New Sound of Politics
authors:
  - name: Robert Bowien
    affiliation: University College Dublin
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Introduction

Politians need to find different means of getting their issues on the public agenda. In the recent years we could observe how populist opposition greatly utilised social media to distribute populist narratives and was successful with it (higher vote shares in parliamentary elections across Europe and there have been populist governments in Italy, Poland, Hungary, Czechia, ...). moderate and non-populist political actors have struggled to withstand the populist shift. This can be partially contributed to their unequal success in utilising social media to communicate and mobilise voters [@mutascu_online_2025; SOURCE].

## Research Question

How has is social media influencing the tone in parliamentary discussions across Europe? And what does it have to do with populism?

Do politicians adjust their tone to generate more reach on social media? If so, does this lead to a more pronounced populist or popular tone? –\> what is the success strategy for which parties on social media?

# Literature Review

Defining populism is a near impossible task, scholars have even referred to this struggle as Cinderella-complex (Aschenputtel-Komplex): There is a shoe formed like populism, but there is no foot fitting the shoe [@priester_rechter_2012]. Nevertheless, one definition has been widely adopted to act as a common baseline understanding of populism; the "ideational" approach. It defines populism as a “thin-centered ideology that considers society to be ultimately separated into two homogeneous and antagonistic groups, ‘the pure people’ versus the ‘corrupt elite,’ and which argues that politics should be an expression of the volonté générale (general will) of the people” [@mudde_populist_2007, p.23].

This definition is kept broad enough to be applied by many scholars, but lacks concrete concepts that would allow for clear operationalisation. Furthermore, this paper examines how populists talk and how they employ rhetoric tactics to communicate their ideas to the electorate. Hence, a definition of populist rhetoric is necessary. To derive a definition of populist rhetoric from a general definition of populism, some degree of deduction is required.

First, the ideology part will be dropped entirely. While populist rhetoric can be used to express ideological ideas, rhetoric itself has no connection to the concept of ideology. Also, while populism is conceptually seen as a sovereign ideology, in reality it is nearly always connected to ideas and concepts of another ideology [@mudde_populism_2017].

Second, the degree to which an argument for politics to express the general will of the people is present in populist rhetoric cannot be measured easily. HIER BEISPIELE MIT SÖDER ISST? –\> appeal to people by appearing "just like the normal people". Making claim that populist express general will of the people also means representing the peoples traits and not only their presumed wants and needs?

This paper therefore aims to use defining concepts that can be translated into measurable variables. Since this work employs means of quantitative text analysis, these variables can adhere closer to the defining concepts than previous studies of populist rhetoric. More elaboration on this can be found in the methods section.

Although there is no consensus about the definition of populist rhetoric, three common traits can be identified: An appeal to "the people", attacking the elites, and ostracising outgroups from the ingroup [@mazzoleni_socially_2018]. This is in line with the ideational definition and an extensive amount of literature relies on these or in their meaning similar concepts [@mazzoleni_socially_2018; @yilmaz_populism_2026; @priester_rechter_2012; @roth_right-wing_2023]. This paper therefore uses the three common traits and adds two more that enhance the grasp of the concept and will be of relevance for operationalisation purposes but have not been used as widely.

First, when viewed from a strategist perspective, definitions of populism include the requirement of a charismatic leader [@mazzoleni_socially_2018; @mudde_populism_2017]. This paper translates a populist movement having a charismatic leader to a trait of populist rhetoric by identifying what kind of rhetoric it needs to establish a charismatic leader. Literature suggests that this kind of rhetoric requires personalisation, direct connection and emotional appeal [@yilmaz_populism_2026; @roth_right-wing_2023].

Second, literature sometimes mentions another aspect of populism: making use of a "glorified heartland" and an "idealized conception of community" [@taggart_populism_2004; @engesser_populism_2017]. This aspect of populism will be incorporated into the definition of populist rhetoric as "retrospective utopia" [@priester_rechter_2012].

Few scholars try to distinguish between types of populist rhetoric. Everything seems to be either populist or not. This lack of conceptual versatility poses a problem since it makes it difficult to understand multi-faceted rhetoric styles. The literature that examines a somewhat weaker or softer form of populism, finds that populists adjust their rhetoric to ensure the medias interest in their messaging [@mazzoleni_media_2003]. This dynamic fosters a continuing diffusion of what is populist and what is popular behaviour [@mazzoleni_media_2003] NEED MORE SOURCES.

If a distinction in literature is made within populist rhetoric, it is rarely commonly conceptualised in detail. Rather, different concepts are used across studies. Some name it "popular rhetoric" [@mazzoleni_media_2003], some "media populism" [@roth_right-wing_2023] or "weak"/"soft"/"moderate" populism [@mazzoleni_socially_2018; @barbieri_populism_2024]. While their contextualisation differs slightly, they are similar in concept. All imply a popular rhetoric that constitutes a somewhat weaker, incomplete form of populist rhetoric. The term popular rhetoric is used to describe aspects of populist rhetoric which have become "popular" and support the adhesion to the masses [@guazina_media_2023; @mazzoleni_media_2003]. Scholars examining media populism embedded the term into a theoretical framework that claims the interplay between the media's need for commercialisation and the populist's desire to be seen changed the way populists behave and talk [@blumler_third_1999; @roth_right-wing_2023]. Moderate populism has been used to classify behaviour that does not fulfill all criteria that a strict definition of populism requires but still is close enough to be classified as populist [@mazzoleni_media_2003; @barbieri_populism_2024].

The term "digital populism", which comes closest to combining these concepts, has only recently achieved greater adaption in the literature [@bartlett_new_2011; @gerbaudo_digital_2024; @yilmaz_populism_2026]. Digital populism is commonly understood as the fusion of the mannerisms of populism with the set of rules and possibilities that come with social media [@yilmaz_populism_2026]. Populists can use social media to distribute their ideas and messages without any filter. This is fundamentally distinct for digital populism.

Some scholars question the narrative of a rise in populism over the last years and indeed find evidence that the claim of rising populism is complicated. In the Netherlands, the occurance of populist rhetoric seems to follow no clear trend. This might be due to self-dooming nature of the anti-establishment rhetoric. After populist parties achieve electoral success, they have joined the establishment and it becomes harder to credibly criticise it [@bos_populist_2014].

This is in line with the claim of populism being endemic in Europe. It has not just risen in the last few years, it has already found its way into political rhetoric across all parties [@mazzoleni_socially_2018]. Populist rhetoric is not exclusive to obviously populist figures. It has become a toolbox for a multitude of political figures to choose from. Ofcourse not every politician uses the same rhetoric tools. One goal of this work is to identify how populist rhetoric differs across parties.

Before the rise of social media politicians ways of communicating with the electorate were restricted to the rules and filters of media outlets and reporters when communicating with the masses. Media was seen as something the politicians needed to become popular. Nowadays, the relationship shifted. Popular politicians are needed by the media to generate engagement and therefore revenue [@mazzoleni_socially_2018]. Instead of the filtering lenses of journalists, the rules of algorithms now dictates which messages are communicated to the masses.

Since it has become evident that politicians successfully utilise this lacking filter via social media, a lot of research on populist rhetoric focused on and supported this claim [@stieglitz2013; @engesser_populism_2017; @mazzoleni_socially_2018; @mutascu_online_2025; @stavrakakis_research_2024; @bos_populist_2014; @bobba_likeability_2018; @blassnig_populist_2021].

Digital media has introduced a quick and intense change into how we think political information is consumed by the electorate. Consuming political online content can contribute to political participation [@kahne_political_2018; @boulianne_social_2015]. Political communication on social media seems to benefit right-wing parties more than left-wing parties [@mutascu_online_2025].

Political communication that employs populist rhetoric on social media differs across parties. Left-wing populists prefer attacks on the economic elite while right-wing populists predominantly attack the media elite and ostracise outgroups [@engesser_populism_2017].

A recent study of party-related posts on social media in Germany showcases that politicians from parties on the political fringes are more engaged and successful in their social media presence. Posts that are in connection to extremer parties are shown much quicker than posts of parties in the political centre [@verwiebe_digitalisiert_2025]. Political entertainment is just one topic displayed on social media feeds along with comedy, lifestyle, technology, gaming, cooking and more. Political information seemlessly reaches broader audiences. This shows the potential of social media as a political tool and also how important it is to employ tactics that play into the preferences of the algorithms.

While most studies mentioned do an important job of showing how social media is used to communicate to the public, no work has been aimed at the core of democratic discourse: the parliament. The parliament is the central institution of every democracy \[SOURCE\]. Its stated purpose is to provide meaningful discussion open to the public to keep the electorate informed and able to hold politicians accountable. Before social media and the internet, parliamentary debates however, have not been as present in peoples everyday life. Who would voluntarily watch debates unfiltered for hours unpaid? Newspapers and TV-news shows have been the filtering lense through which people perceived a curated subset of the words spoken in parliament. Due to social media, most Germans know how the speakers desk of the Bundestag looks like. Snippets of speeches are frequently posted on social media by parties, politicians or other party-affiliated actors. Politicians have an incentive to hold speeches from which short snippets can be extracted. This suggests that speeches have adopted to the new environment.

If the nature of discourse in parliamentary discussions is changing even more towards a purely performative status of permanent campaigning, it becomes debatable if or how it can still fulfill its function of informing citizens about politicians actions.

Foregoing review of the literature tried to establish a meaningful definition for populism that can be operationalised into measurable speech patterns. These patterns will be summarised in the methodological section.

It has also mentioned a link between the use of social media by politicians and the rhetoric patterns in parliamentary speeches. Additionaly it has opened a door to examine the differing ways of populist rhetoric in those parliamentary speeches. This will be elaborated on in the following section on theoretical considerations.

WHAT IS THE RESEARCH GAP?

Some scholars distinguish between different forms of populist rhetoric, but most empirical studies only focus on a dichotomous interpretation of populist rhetoric. Furthermore, existing research demonstrates that populist rhetoric is widely utilised by political actors through social media. The claim politicians speeches in parliament are used to create short videos for social media is a claim often made by news outlets \[SOURCES\], no research has linked a potential change in parliamentary rhetoric to social media yet.

This study aims to adress both. It builds on a theoretical framework for understanding reasons for and differences in rhetorical change in parliaments while aiming to examine this potential change over time demonstrating the link to social media. \[CHANGE IF RESULTS DO NOT SUPPORT THIS LINK\].

# Theory

For political actors it is of crucial importance to be able to effectively communicate their ideas and messages to the electorate. In a quickly changing environment where social media is omnipresent and supports direct, raw and agitating messages, political actors are incentivised to develop new ways of communication that adhere to the rules of the algorithm in some way. Existing literature suggests that populism offers successful tools to achieve this.

It is easier to critizise the ruling elites and exclude outgroups when you are in the opposition. In Germany, the parties known for populist rhetoric are the far left and far right parties which are not in power. We can expect them to use populist rhetoric to a greater extent as they do not have governing power. To therefore conclude that parties of the political centre do not use populist rhetoric would be wrong. Examples of elements of populist rhetoric can be examined across all parties, especially one particular element. Every political leader tries to appeal to the masses, often by pop-cultural ways. From highly professionalised but very approachable looking door-to-door campaigning of Robert Habeck in the latest parliamentary election to professionally unprofessional sausage devouring by Markus Söder, politicians find a way to make the masses feel close to that charismatic political figure.

Hence, it seems that populist rhetoric is employed both in and out of government and even though it takes on different forms, no politician can escape it. The advantage of populist rhetoric lies in its ability to always offers the solution that nobody else offers. To be most credible with this unique solution, it is best to present yourself further away from the mainstream, where you can easily come up with something that is not commonly talked about, something that is unique and plays into the rules of algorithms. This should be easiest for opposition and extreme parties, which is why it can be expected that they were the first to adjust their rhetoric. With the ongoing success, moderate parties had to adjust aswell and even though they do not show their populist tools that obvious, they will have learned to utilise them by now.

## Hypotheses

H1: The general tone of speeches in parliament becomes more populist and more popular??? as social media becomes more relevant.

-   tone and complexity of speeches –\> sentiment analysis score (train model on populist vs popular vs non-pop rhetoric); two different scores per party: how populist and how popular rhetoric

-   look at nikita khokhlovs slides for latent semantic scaling

-   relevance social media –\> different metrics, merged into a score? (more literature needed)

H2a: Parties in opposition are expected to show more populist tone, whereas governing parties are expected to make less use of the populism "critizise the ruling elite" tactic rhetoric.

-   Party position –\> party manifesto? Seating order in Bundestag? expert opinion? (more literature needed)

-   change in tone –\> sentiment analysis score

H2b: Extreme parties in opposition should show the highest level of populist rhetoric

# Methodology

Conduct a sentiment analysis for speeches in the German Bundestag over the last X years.

Correlate with relevance of social media (what measures relevance? user numbers? time spent on / usage frequency of social media? share of people using social media as their main source of information?) --\> which survey data to use?

Idea for descriptive stat:

Check in how many speeches the word gendern occurs across parties in the Bundestag. --\> Hypothesis: populist parties like the AfD and CSU talk a lot about them, others do not. \<-- They set the agenda and aim to make it look like big issue for the other (left-green) parties. Could also do a relative frequency analysis using slides from week 5 (chi²/Keyness analysis). expectation: populist parties will talk more about populist topics lol

# Results and Discussion

## Limitations

This paper is limited to data on parliamentary speeches and unrelated social media metrics. To consolidate inferences about a change in parliamentary rhetoric due to the increased relevance of social media, more data is needed. Matching social media posts with speeches in a quantitative rather than limited descriptive manner (like in this paper) would provide a clear image of which and when specific rhetoric is employed in parliament.

Furthermore, this work does not address the demand side of populist/popular rhetoric on social media. To understand, first, in which cases populist/popular rhetoric generates reach successfully, and second, in which cases digital success translates into political success, the demand side is a crucial, yet under-researched topic \[SOURCE\].

# Conclusion

# NOTES

Look for words that may come from social media culture

look for complexity of speech, social media wants easy stuff, not complicated long sentences, attention span is getting shorter, etc.