# Topic modelling of bundestag speeches of the 20th legislative period


library(tidyr)
library(dplyr)
library(stringfish)
library(stringr)
library(keyATM)
library(quanteda.textstats)
library(quanteda)



bt_speeches <- readRDS("data/bt_speeches.rds")
nrow(bt_speeches)
bt_speeches$doc_id <- seq_len(nrow(bt_speeches))
length(unique(bt_speeches$doc_id))
names_bt_members_list <- unique(bt_speeches$Name) |> list()
names_bt_members <- split(names_bt_members_list[[1]], ceiling(seq_along(names_bt_members_list[[1]])/300))


names_bt_members_rgx <- sapply(names_bt_members, function(names){
  gsub(" \\(.+\\)", "", paste0(names, collapse="|"))
})


removeRegexes <- function(column, regex, n_threads = 4){
  for (n in seq_along(regex)){
    rgx <- regex[n]
    print(paste0("rgx group: ", n, " of ", length(regex)))
    # Source - https://stackoverflow.com/a/78270004
    # Posted by LMc
    # Retrieved 2026-04-08, License - CC BY-SA 4.0
    column <- sf_gsub(column, regex(rgx, ignore_case = TRUE), "", nthreads = n_threads)
  
  }
  return(column)
}

bt_speeches$sentence <- removeRegexes(bt_speeches$sentence, names_bt_members_rgx)

bt_corpus <- corpus(bt_speeches, text_field = "sentence", docid_field = "doc_id")


# Source - https://stackoverflow.com/a/50843894
# Posted by Ken Benoit
# Retrieved 2026-04-29, License - CC BY-SA 4.0

containstarget <- str_detect(bt_corpus, "Drucksachen")
summary(containstarget)
##    Mode   FALSE    TRUE 
## logical    44393     108 

# Source - https://stackoverflow.com/a/50843894
# Posted by Ken Benoit
# Retrieved 2026-04-29, License - CC BY-SA 4.0

bt_corpus_trimmed <- corpus_subset(bt_corpus, !containstarget)

toks <- tokens(
  bt_corpus_trimmed,
  remove_punct = TRUE,
  remove_numbers = FALSE, # some numbers could be relevant as they could refer to specific events (e.g. 100 billion for the Bundeswehr)
  remove_symbols = FALSE
) |>
  tokens_remove(c(stopwords("de"), "kolleginnen", "kollegen", "frau", "herr", "damen", "herren", "geehrte", "geehrten", "liebe", "vielen", "dank", "drucksache", "präsidentin", "präsident", "geehrter", "dr", "dass", "verehrten", "verehrte", "herzlichen", "dank", "ja", "schon", "stimmen", "enthaltungen", "angenommen", "abstimmung", "gestimmt", "ungültige", "neinstimmen", "jastimmen"))




collocations <- textstat_collocations(toks, min_count = 10)
print(collocations[order(-collocations$count),][1:50,])

toks <- tokens_compound(
  toks,
  phrase(c(
    "wer stimmt dagegen",
    "wer stimmt dafür",
    "wer enthält sich",
    "wer stimmt",
    "wer enthält",
    "CDU CSU",
    "CDU csu-fraktion",
    "fraktionen SPD bündnis 90 grünen fdp",
    "fraktion bündnis 90 grünen",
    "bündnis 90 grünen",
    "fraktion CDU CSU",
    "fraktion linke",
    "fraktion SPD",
    "fraktion AfD",
    "fraktion FDP",
    "wladimir putin",
    "europäische union",
    "europäischen union",
    "europäischer union",
    "europäischer rat",
    "europäisches parlament",
    "europäischer gerichtshof",
    "europäische kommission",
    "europäischen kommission",
    "europäische zentralbank",
    "deutschen bundestag",
    "deutscher bundestag",
    "deutsche bundesregierung",
    "demokratische parteien",
    "demokratischen parteien",
    "demokratischen fraktionen",
    "demokratische fraktionen",
    "bürgerinnnen bürger",
    "bürger innen",
    "zuschauer innen",
    "erneuerbare energie",
    "erneuerbare energien",
  ))
)


toks <- toks |> tokens_remove(c("wer_stimmt_dagegen", "wer_stimmt_dafür", "wer_stimmt", "wer_enthält", "wer_enthält_sich"))

kwic_obj <- kwic(toks, pattern = phrase("drucksachen"), window = 1000)
print(kwic_obj[1:3])




dfm <- dfm(toks)
dfm_trim <- dfm_trim(dfm, min_docfreq = 2, min_termfreq = 5)
dfm_trim_clean <- dfm_subset(dfm_trim, ntoken(dfm_trim) > 0)
keyatm_obj <- keyATM_read(dfm_trim_clean)



keyatm_model_15 <- weightedLDA(
  docs = keyatm_obj,
  number_of_topics = 15,
  model = "base",
  options = list(seed = 420)
)

top_words(keyatm_model_15, n = 20)

# create a dataframe that includes the topic probabilities for each document
# disclaimer: this code was generated by perplexity and reviewed and turned into a function by the user.:


create_topic_df <- function(keyatm_model, base_dataframe) {
  
topic_df <- as.data.frame(keyatm_model$theta)
topic_df$doc_id <- seq_len(nrow(topic_df))


# 3) Reshape the 4 dimensions into long format
sentences_long <- base_dataframe |>
  pivot_longer(
    cols = c(People.Centrism, Anti.Elitism, Left.Wing.Host.Ideology, Right.Wing.Host.Ideology),
    names_to = "dimension",
    values_to = "score"
  )

# 4) Join topic proportions
merged <- sentences_long |>
  left_join(topic_df, by = "doc_id")

# 5) Compute topic-weighted averages for each dimension
topic_dims_long <- merged |>
  pivot_longer(
    cols = starts_with("Topic_"),   # adjust if topic columns have different names
    names_to = "topic",
    values_to = "topic_prob"
  )
  
topic_dim_summary <- topic_dims_long |>
  group_by(topic, dimension) |>
  summarise(
    weighted_mean_score = sum(score * topic_prob, na.rm = TRUE) / sum(topic_prob, na.rm = TRUE),
    mean_score = mean(score, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )


topic_dims_long %>%
  group_by(topic) %>%
  summarise(
    total_topic_weight = sum(topic_prob, na.rm = TRUE),
    mean_topic_prob = mean(topic_prob, na.rm = TRUE),
    sd_topic_prob = sd(topic_prob, na.rm = TRUE)
  )


merged <- dplyr::left_join(bt_speeches, topic_df, by = "doc_id")

merged$top_topic <- max.col(merged[, paste0("Topic_", 1:15)], ties.method = "first")

return(merged)

}

merged <- create_topic_df(keyatm_model_15, bt_speeches)

calculate_averages <- function(merged) {
topic_populism <- merged |>
  dplyr::group_by(top_topic) |>
  dplyr::summarise(
    mean_people_centrism = mean(People.Centrism, na.rm = TRUE),
    share_mean_people_centrism = mean(People.Centrism > 0, na.rm = TRUE),
    
    mean_anti_elitism = mean(Anti.Elitism, na.rm = TRUE),
    share_mean_people_centrism = mean(Anti.Elitism > 0, na.rm = TRUE),
    
    mean_left_wing = mean(Left.Wing.Host.Ideology, na.rm = TRUE),
    share_mean_people_centrism = mean(Left.Wing.Host.Ideology > 0, na.rm = TRUE),
    
    mean_right_wing = mean(Right.Wing.Host.Ideology, na.rm = TRUE),
    share_mean_people_centrism = mean(Right.Wing.Host.Ideology > 0, na.rm = TRUE),

    n = dplyr::n()
  )

long <- merged |>
  pivot_longer(starts_with("Topic_"), names_to = "topic", values_to = "p_topic") |>
  mutate(weighted_people_centrism = People.Centrism * p_topic,
         weighted_anti_elitism = Anti.Elitism * p_topic,
         weighted_left_wing = Left.Wing.Host.Ideology * p_topic,
         weighted_right_wing = Right.Wing.Host.Ideology * p_topic)

topic_populism_soft_weighted <- long |>
  group_by(topic) |>
  summarise(
    weighted_mean_people_centrism = sum(weighted_people_centrism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_anti_elitism = sum(weighted_anti_elitism, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_left_wing = sum(weighted_left_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    
    weighted_mean_right_wing = sum(weighted_right_wing, na.rm = TRUE) / sum(p_topic, na.rm = TRUE),
    n = n()
  )

}


topic_populism_soft_weighted <- calculate_averages(merged)
# disclaimer: github copilot generated most of the keywords for the topic analysis, the user adjusted where necessary.
topics = list(agriculture = c("feld", "traktor", "landwirtschaft", "bauern", "ernte", "acker"),
              culturemedia = c("film", "kino", "theater", "kunst", "literatur", "kultur", "tanzen", "feiern"),
              digitalizationtech = c("internet", "digital", "online", "netz", "plattform", "künstliche_intelligenz"),
              echonomy = c("arbeit", "unternehmen", "wirtschaft", "job", "arbeitsplätze", "lohn", "industrie"),
              eudcationscience = c("schule", "bildung", "universität", "forschung", "wissenschaft", "lehrer"),
              environmentclimate = c("klima", "umwelt", "energie", "erneuerbare_energien", "klimaschutz", "klimawandel"),
              financetax = c("steuer", "finanz", "geld", "haushalt", "budget", "schulden"),
              foreign = c("ausland", "international", "europäisch", "diplomatie", "nato", "krieg", "ukraine", "russland", "china", "amerika", "usa"),
              government = c("regierung", "bundesregierung", "kanzler", "minister", "bundestag", "parlament"),
              party = c("partei", "parteien", "fraktion", "abgeordnete", "mitglied", "wahl"),
              regional = c("region", "länder", "bundesländer", "kommunen", "städte", "dörfer"),
              security = c("sicherheit", "polizei", "verfassungsschutz", "terrorismus", "kriminalität"),
              social = c("sozial", "rente", "gesundheit", "pflege", "arbeitslosigkeit", "familie"),
              transportinfrastructure = c("verkehr", "infrastruktur", "bahn", "auto", "flughafen", "straßen", "brücken"),
              procedural = c("antrag", "gesetz", "gesetzesvorlage", "drucksache", "debatte", "abstimmung", "ausschuss", "rede", "plenum")
              )


keyatm_model <- keyATM(
  keyatm_obj,
  model = "base",
  no_keyword_topics = 1,
  keywords = topics,
  options = list(seed = 420)
)

top_words(keyatm_model, n=20)






