---
title: "WIP sometime publish"
format: html
  - name: Robert Bowien
    affiliation: University College Dublin
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Introduction

Watching the prime minister of Bavaria eat sausages and McDonald meals is probably not what citizens from pre-internet Germany imagined political communication would look like in the future. Yet, nowadays politicians like Markus Söder prove that showing approachable personal sides like the consumption of greasy food is a successful way of connecting with the people. Markus Söder has found a way within the set of rules set by the algorithms of social media to connect with the people.

His social media presence features many political messages, but a lot seems non-political and is closer to the appearance of influencer posts. While his food-centered approach is unique in its success, he is by far not the only politician who tries to connect with the people through approachable appearances. Politicians across all parties mix political and seemingly non-political content in their profiles. Ofcourse these posts are just as political as posts with a clear political message.

The currency in democratic politics are votes and the calculation is following: Appealing to the masses by appearing approachable translates to higher reach on social media, higher popularity, higher agenda-setting power and ultimately a higher vote share. This calculation seems to be correct, as Markus Söder has 800 thousand, followers on Instagram, succeeded only by the far-right leader of the AfD Alice Weidel who has over one million followers. Both politicians are often labeled as populists in public discourse and the tactics employed on social media are similar although Weidel does not post lifestyle or food content. The rhetorical tools often resemble each other as they critique the ruling elites (especially during the traffic-light-coalition), establishing an us-vs-them mentality and appealing to the masses in one or another way. The success of right-wing populist politicians does not seem to be random. Moderate and non-populist political actors have struggled to become equally successful utilising social media to communicate and mobilise voters [@mutascu_online_2025; @bobba_likeability_2018].

After satisfying the need for watching meat-dominated food being consumed, one might slide into the political side of social media. Once that happens, one will inevitably also see another type of posts: Snippets of parliamentary speeches of politicians not only from right-wing parties but from across the whole political spectrum.

Before social media and the internet, parliamentary debates however, have not been this present in peoples everyday life. Who would voluntarily watch debates unfiltered for hours unpaid? Newspapers and TV-news shows have been the filtering lense through which people perceived a curated subset of the words spoken in parliament. Due to social media, most Germans know how the speakers desk of the Bundestag looks like. Snippets of speeches are frequently posted on social media by parties, politicians or other party-affiliated actors. Politicians have an incentive to hold speeches from which short snippets that fulfill the conditions the algorithm dictates can be extracted. This suggests that speeches may have adopted to the new environment.

TODO in the end: create a zusammenfassung with logic arrowqs and stuff

## Research Question

The relevance of the possibility of a social-media-fication of parliamentary rhetoric becomes evident when thinking about the purpose of parliamentary debate. If the nature of discourse in parliamentary discussions is changing even more towards a purely performative status of permanent campaigning, it becomes questionable if or how it can still fulfill its function of truthfully informing citizens about politicians actions.

The questions guiding this paper therefore will be following:

How has is social media influencing the tone in parliamentary discussions across Europe? And what does it have to do with populism?

Do politicians adjust their tone in parliamentary speeches to generate more reach on social media? If so, what is the success strategy for which parties and why is it populism?

# Literature Review

A common narrative found in European media outlets is that populism and its rhetorical traits have risen during the last years. Some scholars question this narrative and indeed find evidence that the situation is more complicated. In the Netherlands, the occurance of populist rhetoric seems to follow no clear trend. This might be due to self-dooming nature of the anti-establishment rhetoric. After populist parties achieve electoral success, they have joined the establishment and it becomes harder to credibly criticise it [@bos_populist_2014].

This is in line with the claim of populism being endemic in Europe. It has not risen in the last few years, it has long found its way into political rhetoric across all parties [@mazzoleni_socially_2018]. Populist rhetoric is not exclusive to obviously populist figures. It has become a toolbox for a multitude of political figures to choose from. Ofcourse not every politician uses the same rhetoric tools. One goal of this work is to identify how populist rhetoric differs across parties.

TODO: why am I still expecting an increase over time?

Defining populism is a near impossible task. Scholars have even referred to this struggle as Cinderella-complex (Aschenputtel-Komplex): There is a shoe formed like populism, but there is no foot fitting the shoe [@priester_rechter_2012]. Nevertheless, one definition has been widely adopted to act as a common baseline understanding of populism; the "ideational" approach. It defines populism as a “thin-centered ideology that considers society to be ultimately separated into two homogeneous and antagonistic groups, ‘the pure people’ versus the ‘corrupt elite,’ and which argues that politics should be an expression of the volonté générale (general will) of the people” [@mudde_populist_2007, p.23].

## Modern populist rhetoric

This definition is kept broad enough to be applied by many scholars, but lacks concrete concepts that would allow for clear operationalisation. This paper examines how populists talk and how they employ rhetoric tactics to communicate their ideas to the electorate. Hence, a definition of populist rhetoric is necessary. To derive a definition of populist rhetoric from a general definition of populism, some degree of deduction is required.

First, the ideology part is dropped entirely. While populist rhetoric can be used to express ideological ideas, rhetoric itself has no connection to the concept of ideology. Also, while populism is conceptually seen as a sovereign ideology, in reality it is nearly always connected to ideas and concepts of another ideology [@mudde_populism_2017].

Second, the degree to which an argument for politics to express the general will of the people is present in populist rhetoric cannot be measured easily. Showing yourself eating Bratwurst on social media as the prime minister of Bavaria clearly has political motives. It is a tool to appeal to the masses by representing traits of the masses. Germans like their Bratwurst. This example shows that politicians can use this populist tool not only by expressing a general popular will, but also by displaying traits of the common people.

Due to this variability it is important to define concepts that can be translated into measurable variables. Since this work employs means of quantitative text analysis, these variables can adhere closer to the defining concepts than previous studies of populist rhetoric. More elaboration on this can be found in the methods section.

Although there is no consensus about the definition of populist rhetoric, three common traits can be identified: An appeal to "the people", attacking the elites, and ostracising outgroups from the ingroup [@mazzoleni_socially_2018]. This is in line with the ideational definition and an extensive amount of literature relies on these or in their meaning similar concepts [@mazzoleni_socially_2018; @yilmaz_populism_2026; @priester_rechter_2012; @roth_right-wing_2023]. This paper therefore uses the three common traits and adds two more that enhance the grasp of the concept and will be of relevance for operationalisation purposes but have not been used as widely.

First, when viewed from a strategist perspective, definitions of populism include the requirement of a charismatic leader [@mazzoleni_socially_2018; @mudde_populism_2017]. This paper translates a populist movement having a charismatic leader to a trait of populist rhetoric by identifying what kind of rhetoric it needs to establish a charismatic leader. Literature suggests that this kind of rhetoric requires personalisation, direct connection and emotional appeal [@yilmaz_populism_2026; @roth_right-wing_2023].

Second, literature sometimes mentions another aspect of populism: making use of a "glorified heartland" and an "idealized conception of community" [@taggart_populism_2004; @engesser_populism_2017]. This aspect of populism will be incorporated into the definition of populist rhetoric as "retrospective utopia" [@priester_rechter_2012].

When populism is attached to another ideology, it "thickens" and develops a more distinct nature [@hunger_whats_2022]. If the attached ideology is nativism, scholars call it right-wing populism, if it is socialism, scholars call it left-wing populism [@erhard_popbert_2025]. The nature of right-wing populism that is connected to nativism is exclusionary. It's identity creation stems from excludeing non-native concepts and persons. In contrast left-wing populism that is connected to socialism is inclusionary, claiming to represent marginalized or suppressed groups [@erhard_popbert_2025].

Few scholars try to distinguish between types of populist rhetoric. Everything seems to be either populist or not. This lack of conceptual versatility poses a problem since it makes it difficult to understand multi-faceted rhetoric styles. The literature that examines a somewhat weaker or softer form of populism, finds that populists adjust their rhetoric to ensure the medias interest in their messaging [@mazzoleni_media_2003]. This dynamic fosters a continuing diffusion of what is populist and what is popular behaviour [@mazzoleni_media_2003] NEED MORE SOURCES.

If a distinction in literature is made within populist rhetoric, it is rarely commonly conceptualised in detail. Rather, different concepts are used across studies. Some name it "popular rhetoric" [@mazzoleni_media_2003], some "media populism" [@roth_right-wing_2023] or "weak"/"soft"/"moderate" populism [@mazzoleni_socially_2018; @barbieri_populism_2024]. While their contextualisation differs slightly, they are similar in concept. All imply a popular rhetoric that constitutes a somewhat incomplete form of populist rhetoric. The term popular rhetoric is used to describe aspects of populist rhetoric which have become "popular" and support the appeal to the masses [@guazina_media_2023; @mazzoleni_media_2003]. Scholars examining media populism embedded the term into a theoretical framework that claims the interplay between the media's need for commercialisation and the populist's desire to be seen changed the way populists behave and talk [@blumler_third_1999; @roth_right-wing_2023]. Moderate populism has been used to classify behaviour that does not fulfill all criteria that a strict definition of populism requires but still is close enough to be classified as populist [@mazzoleni_media_2003; @barbieri_populism_2024].

The term "digital populism", which comes closest to combining these concepts, has only recently achieved greater adaption in the literature [@bartlett_new_2011; @gerbaudo_digital_2024; @yilmaz_populism_2026]. Digital populism is commonly understood as the fusion of the mannerisms of populism with the set of rules and possibilities that come with social media [@yilmaz_populism_2026]. Populists can use social media to distribute their ideas and messages without any filter. This is fundamentally distinct for digital populism. The degree of digital populism in politicians rhetoric therefore will be the concept this paper aims to measure and whenever populist rhetoric is mentioned, it is meant to be understood in the context of digital populism.

## Social media and populism

Before the rise of social media politicians ways of communicating with the electorate were restricted to the rules and filters of media outlets and reporters when communicating with the masses. Media was seen as something the politicians needed to become popular. Nowadays, the relationship shifted. Popular politicians are needed by the media to generate engagement and therefore revenue [@mazzoleni_socially_2018]. Instead of the filtering lenses of journalists, the rules of algorithms now dictates which messages are communicated to the masses.

Since it has become evident that politicians successfully utilise this lacking filter via social media, a lot of research on populist rhetoric focused on and supported this claim [@stieglitz2013; @engesser_populism_2017; @mazzoleni_socially_2018; @mutascu_online_2025; @stavrakakis_research_2024; @bos_populist_2014; @bobba_likeability_2018; @blassnig_populist_2021].

Digital media has introduced a quick and intense change into how we think political information is consumed by the electorate. Consuming political online content can contribute to political participation [@kahne_political_2018; @boulianne_social_2015]. Political communication on social media seems to benefit right-wing parties more than left-wing parties [@mutascu_online_2025]. Political communication that employs populist rhetoric on social media differs across parties. Left-wing populists prefer attacks on the economic elite while right-wing populists predominantly attack the media elite and ostracise outgroups [@engesser_populism_2017].

Social media performance plays an increasingly bigger role in parties communication strategies. Parties pay attention to the performance of their social media posts and the engagement with them and adjust their strategy accordingly [@ennser-jedenastik_does_2022]. Since social media proved to be an effective tool for influencing public opinion, political advisors have put more salience on social media [@lilleker_towards_2015]. It is therefore reasonable to assume that parties try to increase their social media reach, for example by using populist rhetoric in speech snippets from parliamentary bodies.

A recent study of party-related posts on social media in Germany showcases that politicians from parties on the political fringes are more engaged and successful in their social media presence. Posts that are in connection to extremer parties are shown much quicker than posts of parties in the political centre [@verwiebe_digitalisiert_2025]. Political entertainment is just one topic displayed on social media feeds along with comedy, lifestyle, technology, gaming, cooking and more. This way, political information seamlessly reaches broader audiences. This shows the high potential of social media as a political tool and also how important it is to employ tactics that play into the preferences of the algorithms.

## The research gap

Some scholars distinguish between different forms of populist rhetoric, but often empirical studies only focus on a dichotomous interpretation of populist rhetoric. Furthermore, existing research demonstrates that populist rhetoric is widely utilised by political actors through social media.

While most studies mentioned do an important job of showing how social media is used to communicate to the public, no work has been aimed at the core of democratic discourse: the parliament. The parliament is the central institution of every democracy \[SOURCE\]. Its stated purpose is to provide meaningful discussion open to the public to keep the electorate informed and able to hold politicians accountable.

Foregoing review of the literature tried to establish a meaningful definition for populism that can be operationalised into measurable speech patterns. These patterns will be summarised in the methodological section.

It has also mentioned a link between the use of social media by politicians and the rhetoric patterns in parliamentary speeches. Additionaly it has opened a door to examine the differing ways of populist rhetoric in those parliamentary speeches. This will be elaborated on in the following section on theoretical considerations.

This study aims to adress both. It builds on a theoretical framework for understanding reasons for and differences in rhetorical change in parliaments while aiming to examine this potential change over time demonstrating the link to social media. \[CHANGE IF RESULTS DO NOT SUPPORT THIS LINK\].

# Theory

For political actors it is of crucial importance to be able to effectively communicate their ideas and messages to the electorate. In a quickly changing environment where social media is omnipresent and supports direct, raw and agitating messages, political actors are incentivised to develop new ways of communication that adhere to the rules of the algorithm in some way. The reviewed literature suggests that populism offers successful tools to achieve this.

It is easier to critizise the ruling elites when you are in the opposition. In Germany, the parties known for populist rhetoric are the far left and far right parties which are not in power. We can expect them to use populist rhetoric to a greater extent as they do not have governing power. To therefore conclude that parties of the political centre do not use populist rhetoric would be wrong. Examples of elements of populist rhetoric can be examined across all parties, especially one particular element. Every political leader tries to appeal to the masses, often by pop-cultural ways. From highly professionalised but very approachable looking door-to-door campaigning of Robert Habeck in the latest parliamentary election to professionally unprofessional sausage devouring by Markus Söder, politicians find a way to make the masses feel close to that charismatic political figure.

Hence, it seems that populist rhetoric is employed both in and out of government and even though it takes on different forms, no politician can escape it. The advantage of populist rhetoric lies in its ability to always offers the solution that nobody else offers. To be most credible with this unique solution, it is best to present yourself further away from the mainstream, where you can easily come up with something that is not commonly talked about, something that is unique and plays into the rules of algorithms. This should be easiest for opposition and extreme parties, which is why it can be expected that they were the first to adjust their rhetoric. With the ongoing success, moderate parties had to adjust aswell and even though they do not show their populist tools that obvious, they will have learned to utilise them by now.


## Hypotheses

Based on the theoretical framework, following hypotheses are specified.

H1: More elements of populist rhetoric will be identified in parliamentary speeches as social media becomes more relevant as a medium of political information.

-   tone and complexity of speeches –\> sentiment analysis score (train model on populist vs popular vs non-pop rhetoric); two different scores per party: how populist and how popular rhetoric

-   look at nikita khokhlovs slides for latent semantic scaling

-   relevance social media –\> different metrics, merged into a score? (more literature needed)

H2a: Parties in opposition are expected to use more elements of populist rhetoric, whereas governing parties are expected to make less use of the "critizise the ruling elite" tactic.

-   Party position –\> party manifesto? Seating order in Bundestag? expert opinion? (more literature needed)

-   change in tone –\> sentiment analysis score

H2b: Extreme parties in opposition should show the highest level of populist rhetoric.

# Methodology

It is still contested and context-dependent how populist rhetoric should be operationalised [@popping_measuring_2018]. Before the availability of transformer models, traditional natural language processing (NLP) often employed dictionary based methods like bag-of-words approaches. These approaches are very reliable and reproducable but face significant challenges when it comes to complex lingual patterns. Populist rhetoric is full of various linguistic tricks which often are not difficult to define and capture. Furthermore, dictionaries designed to capture populism often differ and it is not clear when a dictionary is extensive [@pauwels_chapter_2017].

Recent literature has argued for distinguishing between rational critique of the elites and populist language by adding a moralistic framework to the identifying features [@erhard_popbert_2025].

This paper does not classify the examined speakers as populist or non-populist actors. It relies on a transformer based model to identify populist rhetoric across all types of speakers since the goal of this work is to identify differences in language over time and between parties.

Using a finetuned transformer model has been the quantitative method of choice for most recent research on populist rhetoric. 
Recent research on German populist rhetoric has employed a BERT (Bidirectional Encoder Representations from Transformers) model and fine-tuned it to avoid dichotomous classifying of populism and rather classify aspects of their communications [@erhard_popbert_2025]. 
This paper follows a similar approach in many aspects, but it differs in small, but relevant details. @erhard_popbert_2025 used PopBERT, a fine tuned version of the GBERT model, which is the German version of BERT. Since the model has already been trained on parliamentary speeches from the Bundestag and is fine tuned to identify populist rhetoric, no fine-tuning is needed anymore. It can be directly released on the more recent data this paper aims to examine.

Conduct a sentiment analysis for speeches in the German Bundestag over the last X years.

Correlate with relevance of social media (what measures relevance? user numbers? time spent on / usage frequency of social media? share of people using social media as their main source of information?) --\> which survey data to use?

--> multivariate time series analysis

Idea for descriptive stat:

Check in how many speeches the word gendern occurs across parties in the Bundestag. --\> Hypothesis: populist parties like the AfD and CSU talk a lot about them, others do not. \<-- They set the agenda and aim to make it look like big issue for the other (left-green) parties. Could also do a relative frequency analysis using slides from week 5 (chi²/Keyness analysis). expectation: populist parties will talk more about populist topics lol

# Results and Discussion

## Limitations

This paper is limited to data on parliamentary speeches and unrelated social media metrics. To consolidate inferences about a change in parliamentary rhetoric due to the increased relevance of social media, more data is needed. Matching social media posts with speeches in a quantitative rather than limited descriptive manner (like in this paper) would provide a clear image of which and when specific rhetoric is employed in parliament.

Furthermore, this work does not address the demand side of populist/popular rhetoric on social media. To understand, first, in which cases populist/popular rhetoric generates reach successfully, and second, in which cases digital success translates into political success, the demand side is a crucial, yet under-researched topic \[SOURCE\].

Methodwise, the data has been collected online. This might bias the data towards an audience that is prone to use digital information and therefore overestimate the overall relevance of social media for the electorate.

Additionaly, in some cases, the data does not include full speeches, sometimes, not everything has been sucessfully captured ^[e.g. the speech of an AfD MP: "Frau Präsidentin! Werte Kollegen! Meine Damen und Herren! Vor dem Hintergrund des Krieges in der Ukraine und der offensichtlichen Kriegsverbrechen fällt es durchaus schwer, über die Kriege der 90er-Jahre im ehemaligen Jugoslawien zu sprechen. Auch damals galt – ich ergänze hier das Zitat von Herrn Trittin von von Clausewitz –" is all that is captured in the dataframe when the speech in reality went on for longer. This is the full speech: " Frau Präsidentin! Werte Kollegen! Meine Damen und Herren! Vor dem Hintergrund des Krieges in der Ukraine und der offensichtlichen Kriegsverbrechen fällt es durchaus schwer, über die Kriege der 90er-Jahre im ehemaligen Jugoslawien zu sprechen. Auch damals galt – ich ergänze hier das Zitat von Herrn Trittin von von Clausewitz –: Wenn geschossen wird, statt zu reden, haben Politik und Diplomatie versagt. (Beifall bei der AfD sowie des Abg. Johannes Huber [fraktionslos]) Dass dieses Versagen einen hohen, einen sehr hohen Preis kostet, müssen wir in diesen Tagen schmerzlich als Zuschauer einer fürchterlichen Tragödie in der Ukraine ertragen. Der Zerfall der Bundesrepublik Jugoslawien führte, wie schon gehört, am 5. März 1992 zur Erklärung der Unabhängigkeit der Republik Bosnien und Herzegowina. Bereits vorher hatten Slowenien und Kroatien ihre Unabhängigkeit erklärt, die von Deutschland und anderen schnell anerkannt wurde. In Slowenien griff die jugoslawische Armee ein, wurde jedoch zurückgeschlagen. Aufgrund der weitgehend ethnischen Homogenität der Bevölkerung in Slowenien kam es hier zu keinen inneren Kämpfen. In Bosnien dagegen, wie zuvor schon in Kroatien, brachen unmittelbar nach der Unabhängigkeitserklärung schwere Unruhen aus. Diese führten schließlich in einen grausamen Bürgerkrieg mit wechselnden Beteiligungen der Volksgruppen der Serben, Kroaten und Bosniaken. Schwerste Menschenrechtsverletzungen und Kriegsverbrechen wie ethnische Säuberungen und Massaker an der Zivilbevölkerung fanden auf allen Seiten statt. Das Massaker von Srebrenica mit circa 8 000 Ermordeten wurde gerichtlich als Genozid an den Bosniaken eingestuft. Dem Verfahren vorausgegangen war eine intensive Untersuchung dieses Massenmordes durch eine internationale unabhängige Organisation. Auch für die Kriegsverbrechen von Butscha und anderen Orten in der Ukraine, die in diesen Tagen uns und die Welt bewegen, ist eine solche unabhängige Untersuchung der einzige Weg, um jenseits der Kriegspropaganda Klarheit über die Verantwortlichkeiten zu erlangen. (Beifall bei der AfD sowie des Abg. Johannes Huber [fraktionslos]) Der Krieg in Bosnien endete schließlich nach robuster Intervention der NATO aus der Luft im Dezember 1995 mit dem Abkommen von Dayton. Die Bilanz der bosnischen Tragödie: mehr als 100 000 Tote, mehr als 2 Millionen Flüchtlinge und Vertriebene, davon 350 000 nach Deutschland, schwer zerstörte Infrastruktur und wirtschaftlicher Niedergang, Millionen von Minen im Land mit schrecklichen Folgen für die Bevölkerung, bleibender Hass und tiefes Misstrauen gegenüber den anderen Volksgruppen. 30 Jahre nach der Unabhängigkeitserklärung sind die Folgen des Krieges noch präsent. Die Segregation der Bevölkerung in den serbischen, kroatischen und bosniakischen Anteil ist allgegenwärtig. Der erwähnte Hass auf die anderen Volksgruppen wurde leider von Generation zu Generation weitergegeben. Auch viele Schulen spielten und spielen dabei eine fatale Rolle, wie ich selbst im Laufe eines Einsatzes im gesamten Bosnien feststellen musste. Der ehemalige Hohe Repräsentant Christian Schwarz-Schilling kam frustriert zur gleichen Feststellung. Bosnien-Herzegowina steht immer noch gemäß Dayton-Abkommen unter Überwachung eines Hohen Repräsentanten mit weitreichenden Befugnissen, derzeit des Deutschen Christian Schmidt. Das Abkommen von Dayton, das wichtig war, um 1995 das Blutvergießen zu stoppen, konserviert heute einen dysfunktionalen Staat, der aus zwei Entitäten besteht, zum einen der Föderation der Bosniaken und bosnischen Kroaten und zum anderen der Republik der bosnischen Serben, genannt „Srpska“. Seit der Unabhängigkeit Bosniens gibt es starke Bestrebungen der bosnischen Serben nach staatlicher Unabhängigkeit und der bosnischen Kroaten nach einer dritten Entität. Bisher hat die internationale Gemeinschaft dem nicht nachgegeben. Bosnien-Herzegowina hat 2016 den Antrag auf Aufnahme in die Europäische Union gestellt, und die EU hat diesen Antrag auch angenommen. Allerdings ist der Beginn der Beitrittsverhandlungen in weite Ferne gerückt. Der jüngste Bericht der EU spricht in nahezu allen Reformfeldern von keinen oder nur geringen Fortschritten, ja sogar von Rückschritten. Korruption und Organisierte Kriminalität sind dort nach wie vor endemisch. Die Notwendigkeit, wie wir gehört haben, der Verstärkung der EU-Operation Althea spricht Bände. Milorad Dodik, serbisches Mitglied des Staatspräsidiums, verstärkt derzeit offensichtlich seine Bestrebungen für eine Unabhängigkeit der Republik Srpska. Er erhält dazu Unterstützung aus Serbien und aus Russland. Die Frage, wie der Krieg in der Ukraine nun die Situation in Bosnien und auf dem gesamten Westbalkan beeinflussen wird, ist offen, aber höchst sensitiv. Ich habe Stimmen vernommen, die verlangen, Serbien den Status EU-Kandidat abzuerkennen, weil Serbien sich zum Krieg gegen die Ukraine gegenüber Russland nicht kritisch genug einlässt. Diese Aberkennung wäre fatal und der völlig falsche Weg. (Beifall bei der AfD) Die Bundesregierung und die EU sind daher dringend aufgerufen, durch eine langfristige Strategie und eine kluge Politik für den gesamten Westbalkan die legitimen Interessen aller Beteiligten zu berücksichtigen, ja, auch die Serbiens, der serbischen Bevölkerung Bosniens und des Kosovo. Der Schlüssel zu einem friedlichen Zusammenleben auf dem Westbalkan liegt nämlich auch in Belgrad. Werte Kollegen, es gilt gerade jetzt, durch kluge Politik und Diplomatie zu verhindern, dass in der derzeitigen hochemotionalen Lage in Bosnien und im Kosovo einseitige Entscheidungen zur Sezession getroffen werden. Es muss also unser dringendes Interesse sein, ein dadurch mögliches Übergreifen des Konflikts von der Ukraine auf den Westbalkan zu verhindern. Wie gesagt, der Schlüssel dazu liegt in Belgrad. Dazu muss miteinander geredet werden, und es müssen gangbare Kompromisse gefunden werden – es gibt keinen anderen Weg zur Erhaltung des Friedens in Bosnien-Herzegowina und auf dem Westbalkan. Ich bedanke mich für Ihre Aufmerksamkeit." [@noauthor_plenarprotokoll_2022]].

# Conclusion

# NOTES

Look for words that may come from social media culture

look for complexity of speech, social media wants easy stuff, not complicated long sentences, attention span is getting shorter, etc.